server:
  port: 8081
spring:
  application:
    name: t1-java-demo-guard-service
  datasource:
    url: "jdbc:postgresql://localhost:5477/t1_demo"
    username: "postgres"
    password: "0000"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:29092
      group-id: group-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ru.t1.java.demo.*


logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG

t1:
  scan-path: ru.t1.java.demo
  topic:
    transaction-accept: t1_demo_transaction_accept
    transaction-result: t1_demo_transaction_result
  transaction:
    max-frequency:
      interval: 6000
      count: 10
